name: Deploy to staging

on:
  push:
    branches: ['main']

jobs: 
  redeploy_everything:
    name: Deploy the everything to the staging cluster
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: SSH into the server
        uses: appleboy/ssh-action@v1
        with: 
          host: 13.200.20.200
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="/home/ubuntu/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
             
            cd COHORT3.0-DEVOPS-WEEK-25-2/ 
            git pull
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart ws-server
            pm2 restart next-js-fe